entities/urls.py
from django.urls import path
from . import views

app_name = 'entities'
urlpatterns = [
    path('dlfoldercreate/', views.DLFolderCreateView.as_view(), name='dlfolder-create'),
    path('managercreate/', views.ManagerCreateView.as_view(), name='manager-create'),
    path('downloadercreate/', views.DownloaderCreateView.as_view(), name='downloader-create'),
    path('managers/<int:pk>/update/', views.ManagerUpdateView.as_view(), name='manager-update'),
    path('settings/', views.settings, name='settings'),
    path('managers/', views.managers, name='managers'),
    path('downloaders/', views.downloaders, name='downloaders'),
    path('managers/<int:pk>/test/', views.managertest, name='manager-test'),
]

harpoon2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path("search/", include('dplibs.search', namespace="watson")),
    path('users/', include('users.urls')),
    path('logout', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('entities/', include('entities.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    # path('', views.UserJson.as_view(), name='index'),
    path('<int:userid>/', views.detail, name='detail'),
    path('prefs/', views.userprefs, name='userprefs'),
    ]

entities/models.py
from django.db import models
import os
from harpoon2.settings import MANAGER_TYPES, DOWNLOADER_TYPES
from . import managers, downloaders

# Create your models here.


class DownloadFolder(models.Model):
    folder = models.CharField(max_length=400, unique=True)

    def __str__(self):
        return self.folder


class Manager(models.Model):
    name = models.CharField(max_length=30, unique=True)
    managertype = models.CharField(max_length=20, choices=MANAGER_TYPES)
    url = models.URLField()
    apikey = models.CharField(max_length=50)
    folder = models.ForeignKey(DownloadFolder, on_delete=models.CASCADE)
    label = models.CharField(max_length=25)

    @classmethod
    def from_db(cls, db, field_names, values):
        new = super(Manager, cls).from_db(db, field_names, values)
        # cache value went from the base
        new.client = getattr(managers, new.managertype)(new)
        return new


class Downloader(models.Model):
    name = models.CharField(max_length=30, unique=True)
    downloadertype = models.CharField(max_length=20, choices=DOWNLOADER_TYPES)
    options = models.JSONField(default=dict)

    @classmethod
    def from_db(cls, db, field_names, values):
        new = super(Downloader, cls).from_db(db, field_names, values)
        # cache value went from the base
        new.client = getattr(downloaders, new.downloadertype)(new)
        return new

    # @property
    # def client(self):
    #     return getattr(downloaders, self.downloadertype)(self)

    def checkoptions(self):
        optionfields = self.client.optionfields
        for fieldname in optionfields.keys():
            if fieldname not in self.options.keys():
                if optionfields[fieldname] == 'string':
                    self.options[fieldname] = ''
                elif optionfields[fieldname] == 'int':
                    self.options[fieldname] = 0
                elif optionfields[fieldname] == 'boolean':
                    self.options[fieldname] = False
        self.save()

    def test(self):
        if hasattr(self, 'client'):
            if self.client.reload:
                self.client.__init__(self)
            return self.client.test()

entities/forms.py
from bootstrap_modal_forms.forms import BSModalModelForm
from django.forms import ValidationError
from .models import DownloadFolder, Manager, Downloader
import os

class DLFolderModalForm(BSModalModelForm):
    class Meta:
        model = DownloadFolder
        exclude = ['pk']

    def clean_folder(self):
        data = self.cleaned_data['folder']
        if os.path.exists(data) and os.path.isdir(data):
            return data
        elif os.path.exists(data) and os.path.isfile(data):
            self.add_error('folder', ValidationError('Path exists, but is a file.  Please only enter a folder.'))
        else:
            try:
                os.makedirs(data)
            except PermissionError:

                self.add_error('folder', ValidationError('Folder does not exist and could not be created.  Please check permissions.'))
            except NotADirectoryError:
                self.add_error('folder', ValidationError('Invalid directory.  Check the path and try again.'))
        return data


class ManagerModalForm(BSModalModelForm):
    class Meta:
        model = Manager
        exclude = ['pk']

class DownloaderModalForm(BSModalModelForm):

    def __init__(self, *args, **kwargs):
        super(SchoolModelForm, self).__init__(*args, **kwargs)
        if hasattr(self, 'instance'):
            options = self.instance.options
            for item in options.keys():
                self.fields[f'opt_{item}'] = forms.CharField(required=False, label=f'Personnel ({group})', widget=forms.Textarea)
                self.fields[f'opt_{item}'].initial = PersonList(self.instance.personnel[group]).to_string()

    class Meta:
        model = Downloader
        exclude = ['pk']

entities/views.py
from django.shortcuts import render
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.urls import reverse_lazy, reverse
from . import forms
from . import models
from .managers import Arr, Sonarr, Radarr, Lidarr, Readarr

# Create your views here.

class DLFolderCreateView(BSModalCreateView):
    model = models.DownloadFolder
    template_name = 'entities/dlfoldercreate.html'
    form_class = forms.DLFolderModalForm
    success_message = 'Download folder added.'
    success_url = reverse_lazy('entities:settings')


class ManagerCreateView(BSModalCreateView):
    model = models.Manager
    template_name = 'entities/managercreate.html'
    form_class = forms.ManagerModalForm
    success_message = 'Manager successfully created.'
    success_url = reverse_lazy('entities:managers')


class ManagerUpdateView(BSModalUpdateView):
    model = models.Manager
    template_name = 'entities/managercreate.html'
    form_class = forms.ManagerModalForm
    success_message = 'Manager successfully modified.'
    success_url = reverse_lazy('entities:managers')


class DownloaderCreateView(BSModalCreateView):
    model = models.Downloader
    template_name = 'entities/downloadercreate.html'
    form_class = forms.DownloaderModalForm
    success_message = 'Downloader successfully created.'
    success_url = reverse_lazy('entities:downloaders')


class DownloaderUpdateView(BSModalUpdateView):
    model = models.Downloader
    template_name = 'entities/downloadercreate.html'
    form_class = forms.DownloaderModalForm
    success_message = 'Downloader successfully modified.'
    success_url = reverse_lazy('entities:downloaders')


def settings(request):
    folders = models.DownloadFolder.objects.all()
    return render(request, 'entities/settings.html', {'folders': folders})

def managers(request):
    managers = models.Manager.objects.all()
    return render(request, 'entities/managers.html', {'managers': managers})

def downloaders(request):
    downloaders = models.Downloader.objects.all()
    return render(request, 'entities/downloaders.html', {'downloaders': downloaders})

def managertest(request, pk):
    manager = models.Manager.objects.get(pk=pk)
    if manager.managertype in ['Sonarr', 'Radarr', 'Lidarr', 'Readarr']:
        if manager.managertype == 'Sonarr':
            client = Sonarr(manager)
        elif manager.managertype == 'Radarr':
            client = Radarr(manager)
        elif manager.managertype == 'Readarr':
            client = Readarr(manager)
        else:
            client = Lidarr(manager)
        success, message = client.test()
        return render(request, 'entities/clienttest.html', {'success': success, 'message': message, 'manager': manager})

entities/templates/entities/clienttest.html
 <div class="modal-header">
    <h5 class="modal-title">{{ manager.name }} -- Test</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
 <div>
     <h4>{{ success }}</h4>
     Data: {{ message }}
 </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>

entities/templates/entities/dlfoldercreate.html
{%  load crispy_forms_tags %}
<form method="post" action="{% url 'entities:dlfolder_create' %}" id="createform">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Add Folder</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        {{ field|as_crispy_field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="submit-btn btn btn-primary">Save Changes</button>
  </div>

</form>

entities/templates/entities/downloadercreate.html
{%  load crispy_forms_tags %}
<form method="post" action="{% url 'entities:downloader-create' %}" id="createform">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Modify Manager</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        {{ field|as_crispy_field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="submit-btn btn btn-primary">Save Changes</button>
  </div>

</form>

entities/templates/entities/downloaders.html
{% extends 'base.html' %}

{% block title %}Settings{% endblock %}

{% block content %}
<div>
    <h3>Downloaders <button type="button" id="add-folder" class="bs-modal btn btn-sm btn-primary" data-form-url="{% url 'entities:downloader-create' %}"><i class="fa fa-fw fa-plus-circle"></i> Add Downloader</button></h3>
</div>
    <div class="card-columns">
{% for downloader in downloader %}
        <div id=downloader_info" class="card bg-dark text-white" style="width: 20rem;">

            <div class="card-header bg-primary"><h4 class="card-title">{{ downloader.name }}
                <button type="button" id="edit-downloader" class="bs-modal btn btn-sm btn-primary border-secondary" data-form-url="{% url 'entities:downloader-update' downloader.pk %}"><i class="fa fa-fw fa-pencil-alt"></i></button>
                <button type="button" id="test-downloader" class="bs-modal btn btn-sm btn-primary border-secondary" data-form-url="{% url 'entities:downloader-test' downloader.pk %}"><i class="fa fa-fw fa-fingerprint"></i></button>
                </h4>
            </div>
            <div class="card-body px-1">
                <div><b>URL:</b> {{ downloader. }}</div>
                <div><b>Label:</b> {{ manager.label }}</div>
                <div><b>Folder:</b> {{ manager.folder }}</div>
            </div>
        </div>
{% endfor %}
    </div>
{% endblock %}

entities/templates/entities/managercreate.html
{%  load crispy_forms_tags %}
<form method="post" action="{% url 'entities:manager-create' %}" id="createform">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Modify Manager</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        {{ field|as_crispy_field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="submit-btn btn btn-primary">Save Changes</button>
  </div>

</form>

entities/templates/entities/managers.html
{% extends 'base.html' %}

{% block title %}Settings{% endblock %}

{% block content %}
<div>
    <h3>Managers <button type="button" id="add-folder" class="bs-modal btn btn-sm btn-primary" data-form-url="{% url 'entities:manager-create' %}"><i class="fa fa-fw fa-plus-circle"></i> Add Manager</button></h3>
</div>
    <div class="card-columns">
{% for manager in managers %}
        <div id="manager_info" class="card bg-dark text-white" style="width: 20rem;">

            <div class="card-header bg-primary"><h4 class="card-title">{{ manager.name }}
                <button type="button" id="edit-manager" class="bs-modal btn btn-sm btn-primary border-secondary" data-form-url="{% url 'entities:manager-update' manager.pk %}"><i class="fa fa-fw fa-pencil-alt"></i></button>
                <button type="button" id="test-manager" class="bs-modal btn btn-sm btn-primary border-secondary" data-form-url="{% url 'entities:manager-test' manager.pk %}"><i class="fa fa-fw fa-fingerprint"></i></button>
                </h4>
            </div>
            <div class="card-body px-1">
                <div><b>URL:</b> {{ manager.url }}</div>
                <div><b>Label:</b> {{ manager.label }}</div>
                <div><b>Folder:</b> {{ manager.folder }}</div>
            </div>
        </div>
{% endfor %}
    </div>
{% endblock %}

entities/templates/entities/settings.html
{% extends 'base.html' %}

{% block title %}Settings{% endblock %}

{% block content %}

{% for folder in folders %}
<div>{{ folder }}</div>
{% endfor %}
<button type="button" id="add-folder" class="bs-modal btn btn-sm btn-primary" data-form-url="{% url 'entities:dlfolder_create' %}"><i class="fa fa-fw fa-plus-circle"></i></button>
{% endblock %}