entities/urls.py
from django.urls import path
from . import views

app_name = 'entities'
urlpatterns = [
    path('dlfoldercreate/', views.DLFolderCreateView.as_view(), name='dlfolder-create'),
    path('managercreate/', views.ManagerCreateView.as_view(), name='manager-create'),
    path('downloadercreate/', views.DownloaderCreateView.as_view(), name='downloader-create'),
    path('managers/<int:pk>/update/', views.ManagerUpdateView.as_view(), name='manager-update'),
    path('settings/', views.settings, name='settings'),
    path('managers/', views.managers, name='managers'),
    path('downloaders/', views.downloaders, name='downloaders'),
    path('managers/<int:pk>/test/', views.managertest, name='manager-test'),
]

harpoon2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path("search/", include('dplibs.search', namespace="watson")),
    path('users/', include('users.urls')),
    path('logout', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('entities/', include('entities.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    # path('', views.UserJson.as_view(), name='index'),
    path('<int:userid>/', views.detail, name='detail'),
    path('prefs/', views.userprefs, name='userprefs'),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Harpoon 2{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" type="image/png"  href="{%  static 'images/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{%  static 'images/apple-touch-icon.png' %}"/>
    <link rel="apple-touch-icon-precomposed" href="{%  static 'images/apple-touch-icon.png' %}"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link href="{%  static 'css/sb-admin.css' %}?v=2" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/{{ interface }}/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/select/1.3.1/css/select.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
    <link href="{%  static 'fa/css/all.min.css' %}" rel="stylesheet">
    <link href="{%  static 'css/bootstrap.css' %}?{% now "U" %}" rel="stylesheet">
    <link href="{%  static 'css/jquery-ui.css' %}" rel="stylesheet">
    <link href="{%  static 'css/jquery-ui.structure.css' %}" rel="stylesheet">
    <link href="{%  static 'css/jquery-ui.theme.css' %}" rel="stylesheet">
    <link href="{%  static 'css/attachment.css' %}" rel="stylesheet">
    <link href="{% static 'css/overrides' %}/{{ interface }}.css?{% now "U" %}" rel="stylesheet">
    {% block head %}
    {%  endblock %}
</head>
{% block body %}
  <body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-primary static-top">

      <a class="navbar-brand mr-1" href="/">{{ brandingname }}</a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Navbar Search -->
      <form action="{% url 'watson:search' %}" method="get" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
          <input type="text" id="q" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-dark" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>


      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <span class="badge badge-danger">9+</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>

              <span class="mt-2 d-none d-lg-inline text-white small">{{ user.username }}</span>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              {%  if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'users:userprefs' %}">My Dashboard</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="${http_root}auth/login" data-toggle="modal" data-target="#logoutModal">Logout</a>
              {%  else %}
                <a class="dropdown-item" href="{% url 'login' %}">Login</a>
              {% endif %}
          </div>
        </li>
      </ul>
      </nav>
      <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="{%  url 'home' %}"><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>Dashboard</a>
                    <a class="py-2 nav-link" href="#">
                        <div class="sb-nav-link-icon"><i class="fas fa-fw fa-list-ol"></i></div>
                        <span>Queue</span>
                    </a>
                    <a class="py-2 nav-link" href="#">
                        <div class="sb-nav-link-icon"><i class="fas fa-fw fa-history"></i></div>
                        <span>History</span>
                    </a>
                    <a class="py-2 nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseConfig" aria-expanded="false" aria-controls="collapseConfig">
                        <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                        Config
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseConfig" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'entities:settings' %}">Local Config</a>
                            <a class="nav-link" href="{% url 'entities:managers' %}">Managers</a>
                            <a class="nav-link" href="#">Seedboxes</a>
                            <a class="nav-link" href="{% url 'entities:downloaders' %}">Downloaders</a>
                        </nav>
                    </div>
                    <a class="py-2 nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseSystem" aria-expanded="false" aria-controls="collapseSystem">
                        <div class="sb-nav-link-icon"><i class="fas fa-server"></i></div>
                        System
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                </div>


            </nav>
        </div>
        <div id="layoutSidenav_content">
          <div class="container-fluid py-2">
          {% if messages %}
                {% for message in messages %}
              {% if message.level_tag == "debug" %}
                <div class="alert alert-dark" role="alert">
                    {{  message }}
                </div>
                    {% elif message.level_tag == "error" %}
                <div class="alert alert-danger" role="alert">
                    {{  message }}
                </div>
                    {% else %}
                <div class="alert alert-{{ message.level_tag }}" role="alert">
                    {{  message }}
                </div>
                    {% endif %}
                {% endfor %}
          {% endif %}
            {% block content %}
            {% endblock %}
          </div>
          <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
              <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted align-center">{{ brandingname }}</div>
                  <div class="text-muted">Version {{ version }}</div>
              </div>
            </div>
          </footer>
        </div>
      </div>
      <div id="attachment" title="Attachment">
      </div>

    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">x</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
    {%  endblock %}
    {% block basescripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.3.0.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/alliancekeeper-bs.js' %}?v=1"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/natural.js' %}"></script>
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/sb-admin.js' %}?v=2"></script>
        <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'js/datatableview.js' %}?{% now "U" %}"></script>
    <script type="text/javascript">
        $(function(){
            {%  block embedtables %}
            {% endblock %}
            datatableview.initialize('.datatable');
            var checkbox = $('<input>', {type: 'checkbox', onClick: 'toggleAll(this)'});
            var location = $( "th:contains(zzcheckbox)" );
            location.text('');
            location.append(checkbox);

        });
    </script>
    {% endblock %}
    {% block scripts %}
    {% endblock %}
<script>
    $(function () {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });
    });
</script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="card-deck">
    {% for manager in managers %}
        <div id="manager_info" class="card bg-dark text-white" style="width: 20rem;">

            <div class="card-header bg-primary"><h4 class="card-title">{{ manager.name }}</h4>
            </div>
            <div class="card-body px-1">
                <div><b>URL:</b> {{ manager.url }}</div>
                <div><b>Label:</b> {{ manager.label }}</div>
                <div><b>Folder:</b> {{ manager.folder }}</div>
                <div><b>Version:</b> {{ manager.client.test.1.version }}</div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

{% block content %}
{% load watson %}
    <body>
        <h1>Search results{% if query %} for &ldquo;{{query}}&rdquo;{% endif %}</h1>
        {% if search_results %}
            {% search_results search_results %}
        {% else %}
            {% if query %}
                <p><em>There are no results to display.</em></p>
                <p><em>Try entering a less specific search term.</em></p>
            {% else %}
                <p><em>Please enter a query in the search form.</em></p>
            {% endif %}
        {% endif %}

{{  datatable }}
{% endblock %}
{%  block scripts %}
{% endblock %}